# network architecture
# encoder related
encoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: True
    use_projection: True
    num_layers: 8
    hidden_size: 320
    output_size: 320
# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 300
    atype: location
    adim: 320
    awin: 5
    aheads: 4
    aconv_chans: 10
    aconv_filts: 100
    sampling_probability: 0.0

# hybrid CTC/attention
e2e_conf:
    ctc_weight: 0.5
    lsm_weight: 0.05

# minibatch related
batch_size: 30

# optimization related
optim: adadelta
max_epoch: 15
patience: 3
