# network architecture
# encoder related
elayers: 12
eunits: 2048
# decoder related
dlayers: 6
dunits: 2048
# attention related
adim: 256
aheads: 4

# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 32
maxlen-in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: conformer
accum-grad: 2
grad-clip: 5
patience: 0
epochs: 50
dropout-rate: 0.1

# conformer specific setting
backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_conformer:E2E"
conformer-activation: 'relu'
conformer-input-layer: conv2d     # encoder architecture type
conformer-rel-pos: true
conformer-macaron-style: true
conformer-convolution-block: true
kernel-size: 32
conformer-lr: 1.0
conformer-warmup-steps: 25000
conformer-attn-dropout-rate: 0.0
conformer-length-normalized-loss: false
conformer-init: pytorch
