# minibatch related
batch-size: 2
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced
# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 1
patience: 0

# scheduled sampling option
sampling-probability: 0.0

# encoder related
etype: blstmp     # encoder architecture type
elayers: 2
eunits: 32
eprojs: 32
subsample: "1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 30
context-residual: true
tie-src-tgt-embedding: false
tie-classifier: false
# attention related
atype: add
adim: 32
