# minibatch related
batch-size: 2
maxlen-in: 800
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
epochs: 1
accum-grad: 1
patience: 0
transformer-lr: 5.0
transformer-warmup-steps: 10

# network architecture
## encoder related
etype: transformer
elayers: 1
eunits: 8
subsample: "1_2_2_1_1"
## decoder related
dtype: transformer
dlayers: 1
dunits: 8
## attention related
adim: 8
aheads: 2
## joint network related
joint-dim: 8

# transducer related
## mtlalpha should be set to 1.0 (CTC) to use transducer
mtlalpha: 1.0
## switch to 'rnnt-att' to use transducer with attention
rnnt-mode: 'rnnt'
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
