# minibatch related
batch-size: 2
maxlen-in: 800
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: adadelta
epochs: 1
patience: 0

# network architecture
## encoder related
etype: blstmp
elayers: 2
eunits: 16
eprojs: 16
subsample: "1_2_2_1_1"
## decoder related
dtype: lstm
dlayers: 1
dec-embed-dim: 16
dunits: 16
## attention related
atype: location
adim: 16
aconv-chans: 4
aconv-filts: 3
## joint network related
joint-dim: 16

# transducer related
mtlalpha: 1.0
rnnt-mode: 'rnnt'
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"